from typing import Optional

user_defaults = {
    "hp": 100,
    "accuracy": 10,
    "throws": 0,
    "hits": 0,
    "misses": 0,
    "kills": 0,
    "deaths": 0,
    "items": {"snowball": 1},
}

global_defaults = {
    "items": {
        "SnowBall": {
            "price": 1000,
            "damage": 15,
            "uses": 2,
            "cooldown": 0,
            "accuracy": 95,
            "throwable": True,
            "emoji": "❄️",
        },
        "trident": {
            "price": 2500,
            "damage": 25,
            "uses": 1,
            "cooldown": 30,
            "accuracy": 85,
            "throwable": True,
            "emoji": "🔱",
        },
        "Grenade": {
            "price": 6000,
            "damage": 55,
            "uses": 1,
            "cooldown": 120,
            "accuracy": 77,
            "throwable": True,
            "emoji": "💣",
        },
        "Axe": {
            "price": 3500,
            "damage": 45,
            "uses": 2,
            "cooldown": 90,
            "accuracy": 86,
            "throwable": True,
            "emoji": "🪓",
        },
        "Syringe": {
            "price": 6000,
            "damage": 19,
            "uses": 3,
            "cooldown": 0,
            "accuracy": 96,
            "throwable": True,
            "emoji": "💉",
        },
        "Wrench": {
            "price": 950,
            "damage": 27,
            "uses": 1,
            "cooldown": 5,
            "accuracy": 90,
            "throwable": True,
            "emoji": "🔧",
        },
        "punch": {
            "price": 250,
            "damage": 18,
            "uses": 5,
            "cooldown": 0,
            "accuracy": 96,
            "throwable": True,
            "emoji": "👊",
        },
        "shit": {
            "price": 700,
            "damage": 15,
            "uses": 5,
            "cooldown": 0,
            "accuracy": 98,
            "throwable": True,
            "emoji": "💩",
        },
        "football": {
            "price": 600,
            "damage": 17,
            "uses": 5,
            "cooldown": 0,
            "accuracy": 98,
            "throwable": True,
            "emoji": "🏈",
        },
        "battery": {
            "price": 1700,
            "damage": 25,
            "uses": 2,
            "cooldown": 0,
            "accuracy": 95,
            "throwable": True,
            "emoji": "🔋",
        },
        "bone": {
            "price": 1900,
            "damage": 29,
            "uses": 1,
            "cooldown": 5,
            "accuracy": 89,
            "throwable": True,
            "emoji": "🦴",
        },
        "bomb": {
            "price": 15000,
            "damage": 65,
            "uses": 1,
            "cooldown": 300,
            "accuracy": 75,
            "throwable": True,
            "emoji": "💣",
        },
        "brick": {
            "price": 2200,
            "damage": 35,
            "uses": 1,
            "cooldown": 15,
            "accuracy": 93,
            "throwable": True,
            "emoji": "🧱",
        },
        "dynamite": {
            "price": 17000,
            "damage": 68,
            "uses": 1,
            "cooldown": 300,
            "accuracy": 68,
            "throwable": True,
            "emoji": "🧨",
        },
        "hammer": {
            "price": 5500,
            "damage": 35,
            "uses": 1,
            "cooldown": 5,
            "accuracy": 85,
            "throwable": True,
            "emoji": "🔨",
        },
        "lightening": {
            "price": 22000,
            "damage": 60,
            "uses": 2,
            "cooldown": 30,
            "accuracy": 80,
            "throwable": True,
            "emoji": "⚡",
        },
        "shade": {
            "price": 10,
            "damage": 15,
            "uses": 3,
            "cooldown": 0,
            "accuracy": 98,
            "throwable": True,
            "emoji": "⚫",
        },
        "saturn": {
            "price": 25000,
            "damage": 98,
            "uses": 1,
            "cooldown": 3600,
            "accuracy": 65,
            "throwable": True,
            "emoji": "🪐",
        },
        "rocket": {
            "price": 19000,
            "damage": 80,
            "uses": 2,
            "cooldown": 3600,
            "accuracy": 65,
            "throwable": True,
            "emoji": "🚀",
        },
        "volcano": {
            "price": 23500,
            "damage": 85,
            "uses": 1,
            "cooldown": 1800,
            "accuracy": 55,
            "throwable": True,
            "emoji": "🌋",
        },
        "death": {
            "price": 50000,
            "damage": 200,
            "uses": 3,
            "cooldown": 28800,
            "accuracy": 35,
            "throwable": True,
            "emoji": "✝",
        },
        "health": {
            "price": 1000,
            "damage": 20,
            "uses": 3,
            "cooldown": 10,
            "accuracy": 90,
            "throwable": False,
            "emoji": "💗",
        },
        "MedKit": {
            "price": 2000,
            "damage": 40,  # here damage will actually be the amount it can heal.
            "uses": 2,
            "cooldown": 0,
            "accuracy": 80,  # here accuracy will be the chance of healing completely.
            "throwable": False,
            "emoji": "🩹",
        },
    }
}

dc_fields = [
    ("uses", int),
    ("damage", int),
    ("cooldown", int),
    ("accuracy", int),
    ("throwable", bool),
    ("price", int),
    ("emoji", Optional[str]),
]

lb_types = ["throws", "kills", "deaths", "hits", "misses", "kdr"]
